
/**
 * Constants for main content area.
 */
export class ContentConstants {
  /**
   * The max lines of play all area is 1.
   */
  static readonly PLAY_ALL_MAX_LINES: number = 1;

  /**
   * The font size of the singer is smaller.
   */
  static readonly SINGER_FONT_REDUCE: number = 4;

  /**
   * The font size of the album name is larger.
   */
  static readonly ALBUM_FONT_PLUS: number = 2;

  /**
   * The font size of the introduction is smaller.
   */
  static readonly INTRODUCTION_FONT_REDUCE: number = 2;

  /**
   * Width of the list item divider.
   */
  static readonly DIVIDER_STROKE_WIDTH: number = 0.5;

  /**
   * Aspect ratio of the album cover image.
   */
  static readonly ASPECT_RATIO_ALBUM_COVER: number = 1;

  /**
   * Letter spacing.
   */
  static readonly LETTER_SPACING: number = 1;

  /**
   * Font weight of the album title.
   */
  static readonly ALBUM_FONT_WEIGHT: number = 500;

  /**
   * Font weight of the album introduction.
   */
  static readonly INTRODUCTION_FONT_WEIGHT: number = 400;

  /**
   * Space between cover options.
   */
  static readonly COVER_OPTION_SPACE: number = 4;

  /**
   * Value of lanes is 2.
   */
  static readonly COL_TWO: number = 2;

  /**
   * Value of lanes is 1.
   */
  static readonly COL_ONE: number = 1;
}