
/**
 * Constants for Grid components.
 */
export class GridConstants {
  /**
   * Current component width: 4 grids.
   */
  static readonly SPAN_FOUR: number = 4;

  /**
   * Current component width: 6 grids.
   */
  static readonly SPAN_SIX: number = 6;

  /**
   * Current component width: 8 grids.
   */
  static readonly SPAN_EIGHT: number = 8;

  /**
   * Current component width: 12 grids.
   */
  static readonly SPAN_TWELVE: number = 12;
}