
/**
 * Constants for header area.
 */
export class HeaderConstants {
  /**
   * The font size of the title is larger.
   */
  static readonly TITLE_FONT_SIZE_PLUS: number = 4;

  /**
   * The font weight of the title.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * Letter spacing of the title.
   */
  static readonly LETTER_SPACING: number = 2;

  /**
   * Title bar z-index.
   */
  static readonly Z_INDEX: number = 2;

  /**
   * SystemCapability that indicates audio device management capability.
   */
  static readonly SYSCAP_ETHERNET: string = 'SystemCapability.Multimedia.Audio.Device';

  /**
   * SystemCapability name: audio device service.
   */
  static readonly AUDIO_DEVICE_SERVICE: string = '音频设备管理';

  /**
   * Toast duration is 2000ms.
   */
  static readonly TOAST_DURATION: number = 2000;
}