
/**
 * Routing information on the music page.
 */
export class RouterUrlConstants {
  /**
   * Playback page.
   */
  static readonly MUSIC_PLAY: string = '@bundle:com.huawei.music.musichome/musicPlay/ets/pages/PlayPage';

  /**
   * Music list page.
   */
  static readonly MUSIC_LIST: string = '@bundle:com.huawei.music.musichome/musicList/ets/pages/Index';

  /**
   * Music review page.
   */
  static readonly MUSIC_COMMENT: string = '@bundle:com.huawei.music.musichome/musicComment/ets/pages/Index';
}