
/**
 * Constants for common style.
 */
export class StyleConstants {
  /**
   * Component width percentage: 100%.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Component height percentage: 100%.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Translate value of the collection text.
   */
  static readonly TRANSLATE_X: number = 10;

  /**
   * Translate value of the number of playbacks.
   */
  static readonly TRANSLATE_Y: string = '-100%';

  /**
   * Translate value of the player area on the bottom.
   */
  static readonly TRANSLATE_PLAYER_Y: string = '-48vp';
}