import { Person } from './Person'

export const CONTACTS: Person[] = [
  {
    id: 1,
    weChatImage: "person (1).jpg",
    weChatName: "苏轼",
    chatInfo: "大江东去，浪淘尽，千古风流人物。",
    time: "18:30"
  },
  {
    id: 2,
    weChatImage: "person (2).jpg",
    weChatName: "子由",
    chatInfo: "丙辰中秋，欢饮达旦，大醉，作此篇，兼怀子由。",
    time: "17:29"
  },
  {
    id: 3,
    weChatImage: "person (3).jpg",
    weChatName: "擎苍",
    chatInfo: "老夫聊发少年狂，左牵黄，右擎苍，锦帽貂裘，千骑卷平冈。",
    time: "17:28"
  },
  {
    id: 4,
    weChatImage: "person (4).jpg",
    weChatName: "春水",
    chatInfo: "春未老，风细柳斜斜。试上超然台上望，半壕春水一城花。",
    time: "16:27"
  },
  {
    id: 5,
    weChatImage: "person (5).jpg",
    weChatName: "夜曲",
    chatInfo: "为你弹奏萧邦的夜曲，纪念我死去的爱情",
    time: "15:26"
  },
  {
    id: 6,
    weChatImage: "person (6).jpg",
    weChatName: "不思量",
    chatInfo: "十年生死两茫茫，不思量，自难忘。千里孤坟，无处话凄凉",
    time: "14:25"
  },
  {
    id: 7,
    weChatImage: "person (7).jpg",
    weChatName: "千里之外",
    chatInfo: "我送你离开千里之外你无声黑白",
    time: "13:24"
  },
  {
    id: 8,
    weChatImage: "person (8).jpg",
    weChatName: "思量",
    chatInfo: "似花还似非花，也无人惜从教坠。抛家傍路，思量却是，无情有思。",
    time: "11:23"
  },
  {
    id: 9,
    weChatImage: "person (9).jpg",
    weChatName: "园游会",
    chatInfo: "我顶着大太阳，只想为你撑伞",
    time: "10:22"
  },
  {
    id: 10,
    weChatImage: "person (10).jpg",
    weChatName: "沙湖",
    chatInfo: "三月七日，沙湖道中遇雨。",
    time: "10:21"
  },
  {
    id: 11,
    weChatImage: "person (11).jpg",
    weChatName: "燕子",
    chatInfo: "花褪残红青杏小。燕子飞时，绿水人家绕。枝上柳绵吹又少。",
    time: "10:20"
  },
  {
    id: 12,
    weChatImage: "person (12).jpg",
    weChatName: "衣巾落枣",
    chatInfo: "簌簌衣巾落枣花，村南村北响缲车。牛衣古柳卖黄瓜。",
    time: "10:19"
  },
  {
    id: 13,
    weChatImage: "person (13).jpg",
    weChatName: "七里香",
    chatInfo: "雨下整夜我的爱溢出就像雨水",

    time: "10:18"
  },
  {
    id: 14,
    weChatImage: "person (14).jpg",
    weChatName: "淡烟",
    chatInfo: "细雨斜风作晓寒，淡烟疏柳媚晴滩。",
    time: "10:17"
  },
  {
    id: 15,
    weChatImage: "person (15).jpg",
    weChatName: "大梦",
    chatInfo: "世事一场大梦，人生几度秋凉。",
    time: "10:16"
  }
]

export const WE_CHAT_COLOR: string = "#ededed"