/**
 * 基础常量
 */
export class BaseConstants {
  /**
   * Component size.
   */
  static readonly FULL_HEIGHT: string = '100%';
  static readonly FULL_WIDTH: string = '100%';
  /**
   * Text property.
   */
  static readonly FONT_FAMILY_NORMAL: Resource = $r('app.float.font_family_normal');
  static readonly FONT_FAMILY_MEDIUM: Resource = $r('app.float.font_family_medium');
  static readonly FONT_WEIGHT_FIVE: number = 500;
  static readonly FONT_WEIGHT_FOUR: number = 400;
  static readonly FONT_SIZE_TEN: Resource = $r('app.float.font_size_ten');
  static readonly FONT_SIZE_TWENTY: Resource = $r('app.float.font_size_twenty');
  /**
   * Default icon size.
   */
  static readonly DEFAULT_ICON_SIZE: number = 24;
  /**
   * Device 2in1.
   */
  static readonly DEVICE_2IN1: string = '2in1';
}

